<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_String not Match</name>
   <tag></tag>
   <elementGuidId>82d1f86b-3200-48a3-8797-af613557d5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d60e2d5d-af11-41c6-8320-6bb423d0797d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>String not Match</value>
      <webElementGuid>6b227949-9d21-4fd5-b8a1-72b453ad6c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/h1[1]</value>
      <webElementGuid>b8431a29-fe7e-4f29-8fb4-a7c4c35895d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Compare Strings/iframe_1</value>
      <webElementGuid>4d39d87b-b6b2-4337-8ad3-e05c4266f6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2ed5b121-ad5f-425c-bce8-053a9dadd6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'String not Match' or . = 'String not Match')]</value>
      <webElementGuid>38ae31fe-d260-4584-bd91-09860f069b95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
