<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_String 1_str1</name>
   <tag></tag>
   <elementGuidId>923dbee6-bc0b-4804-ba46-fbfb22f8a002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='str1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#str1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a010e05-c0bb-4478-a849-6498da5a194f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>201908a2-c068-45bc-8e5b-7317c154f55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>str1</value>
      <webElementGuid>8617eff2-87c9-4246-a32d-ce2b17edcad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>str1</value>
      <webElementGuid>25e64765-b1b2-494e-93de-d7cd03364a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;str1&quot;)</value>
      <webElementGuid>5cfb1c56-2195-480a-92d9-04e61577067b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='str1']</value>
      <webElementGuid>8fff8872-3319-4bf0-b026-0bf37005ed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='compare-form']/div/input</value>
      <webElementGuid>1c526ddc-7156-49b2-8d27-bad6e0262470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>647fc025-2db9-4a93-ab37-37345b00b3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'str1' and @name = 'str1']</value>
      <webElementGuid>adacb7c5-cfbb-4f33-bd6c-fe51a9674f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
