<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_str1</name>
   <tag></tag>
   <elementGuidId>d8779c92-cfbb-4612-8743-3026a9a1c756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#str1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='str1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>effc9c3e-a868-4b67-bd08-5bfc942c2a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef990bfe-2e67-44c0-a163-3675d14a855f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>str1</value>
      <webElementGuid>dbd2510e-9456-4373-a453-0e1512b2bb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>str1</value>
      <webElementGuid>d2e5d6cb-4ff5-43e2-8e07-51a20c38a4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;str1&quot;)</value>
      <webElementGuid>c1806f4f-edec-4bea-9dcb-9242f4a8fe26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='str1']</value>
      <webElementGuid>957a675e-20df-4ff1-8c75-9c7fc16217cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='compare-form']/div/input</value>
      <webElementGuid>5d08c417-2ea0-4674-9572-3c0bc9057a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>53ead843-d44c-4595-b60e-f0dcd55ffbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'str1' and @name = 'str1']</value>
      <webElementGuid>c232cf4b-c7e9-451b-810a-6b0f9766202c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
