<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_txt-login</name>
   <tag></tag>
   <elementGuidId>cf0a2d33-40dd-4139-bf1a-6ecd656b3064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-login</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txt-login']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f3aca2b-f26b-48ff-b289-1b8536a6d88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>47de6fbd-dd8a-4e39-8f58-1e80333ead55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>d9ea1131-5abb-4431-8108-0000cce122a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-login</value>
      <webElementGuid>6f0a06ab-2c12-41ea-9711-69e0438586ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-login&quot;)</value>
      <webElementGuid>0379e550-8611-495a-b62f-e8e92365c3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-login']</value>
      <webElementGuid>e2c4ed80-dbe0-4119-b0e6-2c4bc056f938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/main/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>4c150487-824c-47fd-99f8-946690c5f1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bbc19420-44a2-4d1d-9c5d-670fb96f659c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email Address' and @id = 'txt-login']</value>
      <webElementGuid>0283617d-1d50-4cfc-84ea-050f7679a0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
