<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_txt-login</name>
   <tag></tag>
   <elementGuidId>cf0a2d33-40dd-4139-bf1a-6ecd656b3064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-login</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txt-login']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89421615-cd95-45db-aba4-5b4f80f2468c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control</value>
      <webElementGuid>67f16735-bb50-4fae-8099-49dfb45395c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>a4beadac-bb7e-4a11-bbd4-1c16eb24e324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-login</value>
      <webElementGuid>c0ca16a3-f154-411d-b876-8bfc2882d770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-login&quot;)</value>
      <webElementGuid>bbc4c5ef-919a-4704-842a-14b4adae0106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-login']</value>
      <webElementGuid>8cd363bf-ee36-4bff-8ab3-adc9e728cacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/main/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>60b9e120-e1a3-46ca-8a9c-1addd899acc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e049074f-d1fc-4662-9b43-25153bc94650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email Address' and @id = 'txt-login']</value>
      <webElementGuid>2f975290-c560-4bd6-89b2-de28e1a92fe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
